[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ack-unitcalc"
version = "0.1.2"
description = "Pure Python utility library for unit and value calculations"
readme = "README.md"
requires-python = ">=3.8"

authors = [
    { name = "Abhay Chaudhary" }
]

license = "MIT"
license-files = ["LICENSE"]

keywords = [
    "python",
    "calculator",
    "unit-converter",
    "unit-conversion",
    "bmi",
    "temperature",
    "length",
    "weight",
    "volume",
    "time",
    "data"
]

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries",
    "Topic :: Utilities"
]

dependencies = []

[project.urls]
Homepage = "https://github.com/ackwolver335/unitCalc"
Repository = "https://github.com/ackwolver335/unitCalc"
Documentation = "https://github.com/ackwolver335/unitCalc#readme"
"Bug Tracker" = "https://github.com/ackwolver335/unitCalc/issues"

[tool.setuptools.packages.find]
where = ["."]